-- 한번에 정행이랑 나영언니 삭제 고고
-- 삭제가 안된다면 삭제불가 출력
CREATE OR REPLACE PROCEDURE DELMEM
IS
BEGIN
    DELETE FROM EMP WHERE EMP_ID = 4;
    DELETE FROM EMP WHERE EMP_ID = 7;
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END DELMEM;

EXECUTE DELMEM;
SELECT
    *
FROM EMP;

ROLLBACK;

-- 사용자함수
-- 연봉이 200만원이상이면 A등급, 170이상이면 B등급, 150이상이면 C등급 그 이하 D등급 출력
CREATE OR REPLACE FUNCTION FUNC1(SAL EMP.SALARY%TYPE)
RETURN VARCHAR2
IS
    RESULT VARCHAR2(20 BYTE);
BEGIN
    IF SAL >= 2000000 THEN
     RESULT := 'A등급';
    ELSIF SAL >= 1700000 THEN
     RESULT := 'B등급';
    ELSIF SAL >= 1500000 THEN
     RESULT := 'C등급';
     ELSE 
     RESULT := 'D등급';
     END IF;
     RETURN RESULT;
END FUNC1;

SELECT FUNC1(SALARY)
  FROM EMP;
  
-- 트리거
-- 