/*
    수강신청
    1. 여러 학생이 여러 과목을 신청하는 다대다관계
    2. 학생-과목의 직접적인 다대다관계 설정은 불가능
    3. 학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
*/

/*
    참고. 외래키 제약조건을 무시하고 테이블 삭제
    순서에 상관없이 삭제할 수 있음
    DROP TABLE STUDENT CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE ENROLL  CASCADE CONSTRAINTS;
*/

DROP TABLE SUGANG_STUDENT;
CREATE TABLE SUGANG_STUDENT (
    STU_NUM NUMBER(5) NOT NULL,
    STU_NAME VARCHAR2(30 BYTE) NOT NULL,
    STU_AGE NUMBER(3) NULL,
    CONSTRAINT STU_NUM_PK PRIMARY KEY(STU_NUM)
);

DROP TABLE SUGANG_SUBJECT;
CREATE TABLE SUGANG_SUBJECT (
    SJ_CODE VARCHAR2(20 BYTE) NOT NULL,
    SJ_NAME VARCHAR2(20 BYTE) NULL,
    PROP_NAME VARCHAR2(30 BYTE) NULL,
    CONSTRAINT SJ_CODE_PK PRIMARY KEY(SJ_CODE)
);

DROP TABLE SUGANGSINCHUNG;
CREATE TABLE SUGANGSINCHUNG (
    APPLI_CODE NUMBER(3) NOT NULL,
    STU_NUM NUMBER(5) NOT NULL,
    SJ_CODE VARCHAR2(20 BYTE) NOT NULL,
    PRIMARY KEY(APPLI_CODE),
    FOREIGN KEY(STU_NUM) REFERENCES SUGANG_STUDENT(STU_NUM),
    FOREIGN KEY(SJ_CODE) REFERENCES SUGANG_SUBJECT(SJ_CODE)
);