-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK_TBL;

-- BANK 테이블 생성
CREATE TABLE BANK (
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE) NOT NULL
);

-- CUSTOMER 테이블 생성
CREATE TABLE CUSTOMER (
    NO NUMBER          NOT NULL,
    NAME VARCHAR2(30)  NOT NULL,
    PHONE VARCHAR2(30)      UNIQUE,
    AGE NUMBER(3)      CHECK(AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20)
);
-- 기본키 추가
ALTER TABLE BANK ADD CONSTRAINT PK_BANK_CODE PRIMARY KEY(BANK_CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(NO);

-- 외래키 추가
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_BANK_CODE FOREIGN KEY(BANK_CODE)
    REFERENCES BANK(BANK_CODE)
    ON DELETE CASCADE; -- 참조하고 있는 PK가 지워지면 같이 지워지겠다.

/*
    FK 옵션
    
    1. ON DELETE SET NULL
        1) 참조하던 PK의 값이 삭제되면 FK의 값을 NULL로 수정
        2) 회원 탈퇴 시 작성한 게시글 모두 삭제, 게시글 삭제 시 달린 댓글 모두 삭제와 같은 경우
    2. ON DELETE CASCADE
        1) 참조하던 PK의 값이 삭제되면 FK의 값을 함께 삭제
        2) 회원 탈퇴 시 작성한 게시글 모두 삭제, 게시글 삭제 시 달린 댓글 모두 삭제와 같은 경우
    
*/


-- 테이블 변경하기(ALTER TABLE)
-- 1. 칼럼추가 : ALTER TABLE 테이블 ADD 칼럼명 데이터타입 [제약조건]
-- 2. 칼럼수정 : ALTER TABLE 테이블 MODIFY 칼럼명 데이터타입 [제약조건] - 데이터타입은 생략불가능 제약조건은 가능
-- 3. 칼럼삭제 : ALTER TABLE 테이블 DROP COLUMN
-- 4. 칼럼이름 : ALTER TABLE 테이블 RENAME COLUMN 0LD이름 TO NEW이름
-- 5. 테이블이름 : ALTER TABLE 테이블 RENAME TO NEW이름
-- * COLUMN수정하는건 테이블수정이라고 부른다. ROW수정하는건 테이블 수정이라 하지않는다.


-- 1. BANK 테이블에 BANK_PHONE 칼럼을 추가하시오.
ALTER TABLE BANK
    ADD PHONE VARCHAR2(20 BYTE) NULL;

-- 2. CUSTOMER 테이블에 GRADE 칼럼을 추가하시오. ('VIP', 'GOLD', 'SILVER' 중 하나의 값만 가진다.)
ALTER TABLE CUSTOMER
    ADD GRADE VARCHAR2(6 BYTE) CHECK(GRADE IN('VIP', 'GOLD', 'SILVER')); -- GRADE IN() : GRADE가 이 안에 있다.


-- 3. BANK 테이블의 BANK_NAME 칼럼을 VARCHAR2(15 BYTE)로 수정하시오.
ALTER TABLE BANK
    MODIFY BANK_NAME VARCHAR2(15 BYTE);

-- 4. BANK 테이블의 BANK_NAME 칼럼을 NOT NULL로 수정하시오.
ALTER TABLE CUSTOMER
    MODIFY BANK_CODE VARCHAR2(15 BYTE) NOT NULL;

-- 5. CUSTOMER 테이블의 AGE 칼럼을 삭제하시오.
ALTER TABLE CUSTOMER
    DROP COLUMN AGE;


-- 6. CUSTOMER 테이블의 NO 칼럼과 NAME 칼럼이름을 CUST_NO와 CUST_NAME으로 변경하시오.
ALTER TABLE CUSTOMER
    RENAME COLUMN NO TO CUST_NO;
ALTER TABLE CUSTOMER
    RENAME COLUMN NAME TO CUST_NAME;

-- 7. BANK 테이블의 이름을 BANK_TBL로 수정하시오.
ALTER TABLE BANK RENAME TO BANK_TBL;
