
-- 교수
CREATE TABLE PROFESSOR (
    PROF_NO NUMBER              NOT NULL,
    PROF_NAME VARCHAR2(20 BYTE) NOT NULL,
    PROF_MJ VARCHAR2(20 BYTE)   NOT NULL
);
-- 과목
CREATE TABLE COURSE (
    SJ_NO NUMBER                NOT NULL,
    SJ_NAME VARCHAR2(20 BYTE)   NOT NULL,
    SJ_STU_SCORE NUMBER(1, 2)   NOT NULL
);
-- 학생
CREATE TABLE STUDENT (
     STU_NO NUMBER(8)           NOT NULL,
     STU_NAME VARCHAR2(20 BYTE) NOT NULL,
     STU_ADDR VARCHAR2(50 BYTE),
     GRADE NUMBER(1)            NOT NULL,
     STU_PROF_NO NUMBER         NOT NULL
);
-- 강의
CREATE TABLE LECTURE (
    LECT_NO NUMBER(3)           NOT NULL,
    PROF_NO NUMBER              NOT NULL,
    ENR_NO NUMBER               NOT NULL,
    LECT_NAME VARCHAR2(20 BYTE) NOT NULL,
    LECT_ROOM VARCHAR2(20 BYTE) NOT NULL
);
-- 수강신청
CREATE TABLE ENROLL (
    ENR_NO NUMBER               NOT NULL,
    STU_NO NUMBER(8)            NOT NULL,
    SJ_NO NUMBER                NOT NULL,
    ENR_DATE DATE               NOT NULL
);




-- PK
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STU_NO PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROF_NO PRIMARY KEY(PROF_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_SJ_NO PRIMARY KEY(SJ_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENR_NO PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECT_NO PRIMARY KEY(LECT_NO);

-- FK
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_PROF_NO_ST FOREIGN KEY(STU_PROF_NO) 
    REFERENCES PROFESSOR(PROF_NO)
    ON DELETE CASCADE;
    
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_PROF_NO_LEC FOREIGN KEY(PROF_NO)
    REFERENCES PROFESSOR(PROF_NO)
    ON DELETE SET NULL;
    
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENR_NO FOREIGN KEY(ENR_NO)
    REFERENCES LECTURE(ENR_NO)
    ON DELETE CASCADE;

