DROP SEQUENCE SEQ_POST;
CREATE SEQUENCE SEQ_POST NOCACHE;


DROP TABLE POST;
CREATE TABLE POST (
	POST_NO     NUMBER              NOT NULL,
	WRITER      VARCHAR2(30 BYTE)   NOT NULL,
	TITLE       VARCHAR2(100 BYTE) 	NOT NULL,
	CONTENT     VARCHAR2(400 BYTE),
	VIEWS       NUMBER              NOT NULL,
	POST_DATE   DATE,
	MODIFY_DATE DATE,
	IP          VARCHAR2(50 BYTE),
	CONSTRAINT PK_POST PRIMARY KEY(POST_NO)
);