DROP SEQUENCE BOARD_SEQUENCE;
CREATE SEQUENCE BOARD_SEQUENCE START WITH 1000 NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD (
    BOARD_NO NUMBER NOT NULL,
    WRITER VARCHAR2(20 BYTE),
    TITLE VARCHAR2(100 BYTE),
    CONTENT VARCHAR2(500 BYTE),
    WRITE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);