DROP SEQUENCE CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ NOCACHE;

DROP TABLE CONTACT;
CREATE TABLE CONTACT(
    NO      NUMBER              NOT NULL,
    NAME    VARCHAR2(100 BYTE)  NOT NULL,
    TEL     VARCHAR2(100 BYTE),
    ADDR    VARCHAR2(100 BYTE)  NOT NULL,
    EMAIL   VARCHAR2(100 BYTE),
    NOTE    VARCHAR2(100 BYTE),
    CONSTRAINT PK_CONTACT PRIMARY KEY (NO)
);

INSERT INTO CONTACT(NO, NAME, TEL, ADDR, EMAIL, NOTE) VALUES(CONTACT_SEQ.NEXTVAL, '히랭이', '010-1234-5678', '신림동', 'djagmlfk@naver.com', '본인');
COMMIT;